# Generated by Django 4.0.1 on 2022-03-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='payment',
            new_name='donate',
        ),
    ]
