# Generated by Django 4.0.1 on 2022-03-07 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0002_rename_payment_donate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='donate',
            new_name='Coffee',
        ),
    ]
